############################################################

function(output_compile_flags)
    MESSAGE("${PROJECT_NAME} Build Type = ${CMAKE_BUILD_TYPE}")
    MESSAGE("${PROJECT_NAME} CMAKE_CXX_FLAGS = ${CMAKE_CXX_FLAGS}")
    MESSAGE("${PROJECT_NAME} CMAKE_C_FLAGS = ${CMAKE_C_FLAGS}")
    MESSAGE("${PROJECT_NAME} CMAKE_CXX_FLAGS_RELEASE = ${CMAKE_CXX_FLAGS_RELEASE} CMAKE_C_FLAGS_RELEASE = ${CMAKE_C_FLAGS_RELEASE}")
    MESSAGE("${PROJECT_NAME} CMAKE_CXX_FLAGS_DEBUG = ${CMAKE_CXX_FLAGS_DEBUG} CMAKE_C_FLAGS_DEBUG = ${CMAKE_C_FLAGS_DEBUG}")
endfunction()

